#!/bin/bash
cd src
python -m py_compile bot.py util.py BotLayer.py StrategyLayer.py TacticsLayer.py MicroLayer.py
if [[ $? != 0 ]]; then
	echo -e "\nPython compilation failed, aborting packaging process"
	exit 1
fi
zip -rj bot.zip bot.py util.py BotLayer.py StrategyLayer.py TacticsLayer.py MicroLayer.py
cd ..
mv ./src/bot.zip ./bot.zip
if [[ $# > 0 ]]; then
	cp ./bot.zip $1
fi
