#!/bin/bash
cd src
python -m py_compile bot.py util.py BotLayer.py StrategyLayer.py TacticsLayer.py MicroLayer.py
if [[ $? != 0 ]]; then
	echo -e "\nPython compilation failed, aborting packaging process"
	exit 1
fi
zip -rj bot.zip bot.py util.py BotLayer.py StrategyLayer.py TacticsLayer.py MicroLayer.py
mv ./bot.zip ../bot.zip	
